# -*- coding: utf-8 -*-
"""Assignment 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11sY5eWzHgq3n0w_Ae33B7-XtNlbGzLSv
"""

# Rigor and Reproducibility
# Assignment 7
# 11/1/2023

from datetime import date
today = date.today()
print(today)

print(2*5)

# Using data repositories are extremely important in research because they are large databases which can be used to collect, manage, and store data sets.
# This allows practically anyone to access these resources for their own data analysis.
# Repositories with organizational structures already in place make sharing and reporting data much easier and more accessible.
# It also allows researchers to combine data from many different institutions, allowing scientists to increase the statistical significance of their studies.
# Additionally, the ability to track changes allows one to track the progress that has been made. This also allows you to go back to previous versions of the code.
# And publishing repositories like GitHub allow scientists from all disciplines and from all over the world to access previously written programs.
# This increases reproducibility by giving scientists attempting to recreate an experiment/analysis method access to everything used in the original study.
# It also allows other scientists to refer to others' code to enhance their own studies.